# Generated by Django 5.1.1 on 2024-09-20 13:04

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_remove_video_user_alter_video_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to=''),
        ),
    ]
